export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST" 
export const CREATE_ORDER_ = "CREATE_ORDER_" 
export const CREATE_ORDER_ = "CREATE_ORDER_"

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST" 
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST" 
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST" 
