export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCT_BY_ID_REQUEST" 
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS" 
export const FIND_PRODUCT_BY_ID_FALIURE = "FIND_PRODUCT_BY_ID_FAILURE"

export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCTREQUEST" 
export const FIND_PRODUCTSUCCESS = "FIND_PRODUCTSUCCESS" 
export const FIND_PRODUCTFAILURE = "FIND_PRODUCTFAILURE" 